spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: ${SPRING_DATABASE_URL}
        username: ${SPRING_DATABASE_USERNAME}
        password: ${SPRING_DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            database: postgresql
            database-platform: org.hibernate.dialect.PostgreSQLDialect
            open-in-view: false
            generate-ddl: true
